Models/ErrorViewModel.cs
using System;

namespace WeeNote.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Note.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WeeNote.Models{
    public class Note
    {
        public int Id { get; set; }
        public string NoteTitle { get; set; }
        public string NoteText { get; set; }
        public string Tag { get; set; }

        public Note()
        {

        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WeeNote.Models;

namespace WeeNote.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NotesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WeeNote.Data;
using WeeNote.Models;

namespace WeeNote.Controllers
{
    public class NotesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NotesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Notes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Note.ToListAsync());
        }

        public async Task<IActionResult> ViewResultsTitle(String searchingtitle)
        {
            return View("Index", await _context.Note.Where(k => k.NoteTitle.Contains(searchingtitle)).ToListAsync());
        }
        public async Task<IActionResult> ViewResultsTag(String searchingtag)
        {
            return View("Index", await _context.Note.Where(l => l.Tag.Contains(searchingtag)).ToListAsync());
        }
        public async Task<IActionResult> ViewResultsText(String searchingtext)
        {
            return View("Index", await _context.Note.Where(j => j.NoteText.Contains(searchingtext)).ToListAsync());
        }

        public async Task<IActionResult> Searching()
        {
            return View("Searching");
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .FirstOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // GET: Notes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NoteTitle,NoteText,Tag")] Note note)
        {
            if (ModelState.IsValid)
            {
                _context.Add(note);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }


        // GET: Notes/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note.FindAsync(id);
            if (note == null)
            {
                return NotFound();
            }
            return View(note);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NoteTitle,NoteText,Tag")] Note note)
        {
            if (id != note.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(note);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoteExists(note.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(note);
        }

        // GET: Notes/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .FirstOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }



        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var note = await _context.Note.FindAsync(id);
            _context.Note.Remove(note);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NoteExists(int id)
        {
            return _context.Note.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
 @{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to the WeeNote application</h1>
    <p><a href="https://yoomoney.ru/to/410012018566263">Consider supporting if you want to see more</a>.</p>
    <p>and have fun</p>

    <form asp-action="Create">
        <a asp-controller="Notes" asp-action="Create" class="btn-dark">MAKE A NOTE</a>
    </form>
    <form asp-action="Index">
        <a asp-controller="Notes" asp-action="Index" class="btn-dark">watch your notes</a>
    </form>
    <form asp-action="Searching">
        <a asp-controller="Notes" asp-action="Searching" class="btn-dark">search for note</a>
    </form>
</div>

Views/Notes/Create.cshtml
@model WeeNote.Models.Note

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Note</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NoteTitle" class="control-label"></label>
                <input asp-for="NoteTitle" class="form-control" />
                <span asp-validation-for="NoteTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoteText" class="control-label"></label>
                <input asp-for="NoteText" class="form-control" />
                <span asp-validation-for="NoteText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tag" class="control-label"></label>
                <input asp-for="Tag" class="form-control" />
                <span asp-validation-for="Tag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Notes/Delete.cshtml
@model WeeNote.Models.Note

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Note</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoteTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoteTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoteText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoteText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tag)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Notes/Details.cshtml
@model WeeNote.Models.Note

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Note</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoteTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoteTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoteText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoteText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tag)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Notes/Edit.cshtml
@model WeeNote.Models.Note

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Note</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="NoteTitle" class="control-label"></label>
                <input asp-for="NoteTitle" class="form-control" />
                <span asp-validation-for="NoteTitle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoteText" class="control-label"></label>
                <input asp-for="NoteText" class="form-control" />
                <span asp-validation-for="NoteText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tag" class="control-label"></label>
                <input asp-for="Tag" class="form-control" />
                <span asp-validation-for="Tag" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Notes/Index.cshtml
@model IEnumerable<WeeNote.Models.Note>

@{
    ViewData["Title"] = "Index";
}

<table class="table" border="0">
    <tbody>
        @foreach (var item in Model)
        {
        <tr style="border: hidden">
            <td>@Html.DisplayFor(modelItem => item.NoteTitle)</td>
            <td class="btn btn-primary">
                @Html.DisplayFor(modelItem => item.Tag)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>

        </tr>
    <td style="border: hidden">✎ @Html.DisplayFor(modelItem => item.NoteText)<p><p><p><p><p><p></td>



        }
    </tbody>
    </table>
<p>
    <a asp-action="Create">Add one more</a>
</p>

Views/Notes/Searching.cshtml
@model Note 
<h4>Searching</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ViewResultsTitle">
            <div class="form-group">
                <label for="male">search by title</label>
                <input name="searchingtitle" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Go Search!" class="btn btn-primary" />
                
            </div>
        </form>
        <form asp-action="ViewResultsTag">
            <div class="form-group">
                <label for="male">search by tag</label>
                <input name="searchingtag" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Go Search!" class="btn btn-primary" />
            </div>
        </form>
        <form asp-action="ViewResultsText">
            <div class="form-group">
                <label for="male">search by text inside note</label>
                <input name="searchingtext" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Go Search!" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeeNote</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WeeNote</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <div class="form-group">
                            <a href="https://github.com/WithJobs" class="btn btn-primary">GitHub</a>
                        </div>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - WeeNote - Designed by Pavel Mulyarchik</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>